language: java
sudo: required
jdk:
  - oraclejdk8
install: 
  - cd desapp-groupA-backend/
  - mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
script: 
  - mvn test jacoco:report -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
after_script:
  - cd ..
  - git clone https://github.com/codacy/codacy-coverage-reporter.git
  - cd codacy-coverage-reporter/
  - sbt assembly 
  - java -cp target/codacy-coverage-reporter-assembly-1.0.4.jar com.codacy.CodacyCoverageReporter -l Java -r ../desapp-groupA-backend/target/site/jacoco/jacoco.xml
